[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  PAYLOAD_SECRET = "b28364e3561544cba49e5e3f"
  DATABASE_URI = "mongodb+srv://dina_2017_suvadu:mCrxkke1vdluuvwR@dinasuvaducms.tbyygei.mongodb.net/dinasuvaducms?retryWrites=true&w=majority&appName=dinasuvaducms"
